name: Build and deploy

on:
  push: 
    branches: [ main ]

  # Run workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Create environment file
        run: |
          echo "export const environment = {" > ./src/environments/environment.ts
          echo "  production: true," >> ./src/environments/environment.ts
          echo "  UNSPLASH_API_KE: '${{ secrets.UNSPLASH_API_KE }}'," >> ./src/environments/environment.ts
          echo "  OPENSEA_API_KEY: '${{ secrets.OPENSEA_API_KEY }}'" >> ./src/environments/environment.ts
          echo "};" >> ./src/environments/environment.ts
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with: 
          name: dist
          path: dist/historias-do-brasil/browser
  deploy: 
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist/historias-do-brasil/browser
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          OPENSEA_API_KEY: ${{ secrets.OPENSEA_API_KEY }}
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
